/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IErrorLog } from "./models/log";
export { IErrorLog } from "./models/log";
export namespace Components {
    interface ComponentGamePokerSquares {
        "birth_year"?: number;
        "custom_lang"?: ("hu" | "en");
        "difficulty": number;
        "disable_log": boolean;
        "education"?: string;
        "enable_narration"?: boolean;
        "pause": () => Promise<void>;
        "player_id": any;
        "probe_mode": boolean;
        "region": number;
        "restart": () => Promise<void>;
        "resume": () => Promise<void>;
        "sex"?: number;
        "stop": () => Promise<void>;
        "token"?: string;
    }
}
export interface ComponentGamePokerSquaresCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLComponentGamePokerSquaresElement;
}
declare global {
    interface HTMLComponentGamePokerSquaresElement extends Components.ComponentGamePokerSquares, HTMLStencilElement {
    }
    var HTMLComponentGamePokerSquaresElement: {
        prototype: HTMLComponentGamePokerSquaresElement;
        new (): HTMLComponentGamePokerSquaresElement;
    };
    interface HTMLElementTagNameMap {
        "component-game-poker-squares": HTMLComponentGamePokerSquaresElement;
    }
}
declare namespace LocalJSX {
    interface ComponentGamePokerSquares {
        "birth_year"?: number;
        "custom_lang"?: ("hu" | "en");
        "difficulty"?: number;
        "disable_log"?: boolean;
        "education"?: string;
        "enable_narration"?: boolean;
        "onComponentLoaded"?: (event: ComponentGamePokerSquaresCustomEvent<void>) => void;
        "onFinish"?: (event: ComponentGamePokerSquaresCustomEvent<any>) => void;
        "onGameError"?: (event: ComponentGamePokerSquaresCustomEvent<IErrorLog>) => void;
        "onNarrationChanged"?: (event: ComponentGamePokerSquaresCustomEvent<boolean>) => void;
        "player_id"?: any;
        "probe_mode"?: boolean;
        "region"?: number;
        "sex"?: number;
        "token"?: string;
    }
    interface IntrinsicElements {
        "component-game-poker-squares": ComponentGamePokerSquares;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "component-game-poker-squares": LocalJSX.ComponentGamePokerSquares & JSXBase.HTMLAttributes<HTMLComponentGamePokerSquaresElement>;
        }
    }
}
